server:
  port: 8004

spring:
  application:
    name: core
  jpa:
    hibernate:
      ddl-auto: validate
  flyway:
    schemas: core_schema
    default-schema: core_schema

jwt:
  secret: ${JWT_SECRET:TTdGFPf9lbnQ3J3GBU8MnwQfp3oaawcBzf9LlBJpqlE=}

internal:
  api-key: ${INTERNAL_API_KEY:H5A1u/lQOivHU+ziG0/oEWUa2oF3uXdZVmuYZH8siFA=}
