server:
  port: 8001

spring:
  application:
    name: auth
  jpa:
    hibernate:
      ddl-auto: validate
  flyway:
    schemas: auth_schema
    default-schema: auth_schema

jwt:
  secret: ${JWT_SECRET:TTdGFPf9lbnQ3J3GBU8MnwQfp3oaawcBzf9LlBJpqlE=}
  access-token-expiration-ms: ${JWT_ACCESS_EXPIRATION_MS:900000}
  refresh-token-expiration-ms: ${JWT_REFRESH_EXPIRATION_MS:2592000000}
